name: appexpflutter_update
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  api_client:
    path: packages/api_client
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  mobile_scanner: ^5.1.1
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  reactive_forms: ^17.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  open_file: ^3.3.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/iconos/
    - google_fonts/montserrat_alternates/
