import 'package:appexpflutter_update/features/historial/domain/entities/detalle_sesion_entity.dart';
import 'package:appexpflutter_update/features/precios/domain/entities/producto_entity.dart';

mixin ProductoSesion {
  DetalleSesionEntity convertToDetalleSesionEntity(ProductoEntity producto) {
    return DetalleSesionEntity(
      idDetallesesion: 0,
      idSesion: 0,
      clave: producto.producto1,
      clave2: producto.producto,
      cantidad: 0,
      precio: 0,
      importe: 0,
      estatus: 0,
      cerrado: 0,
      pedidos: '',
      producto: producto.producto,
      producto1: producto.producto1,
      descripcio: producto.descrip,
      diseno: producto.diseno,
      medidas: producto.medidas,
      largo: producto.largo,
      ancho: producto.ancho,
      rojo: producto.rojo,
      precio1: producto.precio1,
      precio2: producto.precio2,
      precio3: producto.precio3,
      pathima1: producto.pathima1,
      pathima2: producto.pathima2,
      pathima3: producto.pathima3,
      pathima4: producto.pathima4,
      pathima5: producto.pathima5,
      pathima6: producto.pathima6,
      desa: producto.desa,
      color1: producto.color1,
      color2: producto.color2,
      color3: producto.color3,
      unidad: producto.unidad,
      compo1: producto.compo1,
      compo2: producto.compo2,
      lava1: producto.lava1,
      lava2: producto.lava2,
      coo: producto.coo,
      origenn: producto.origenn,
      fecha: producto.fecha,
      video1: producto.video1,
      cunidad: producto.cunidad,
      ccodigosat: producto.ccodigosat,
      precio4: producto.precio4,
      precio5: producto.precio5,
      precio6: producto.precio6,
      precio7: producto.precio7,
      precio8: producto.precio8,
      precio9: producto.precio9,
      precio10: producto.precio10,
      fulldescrip: producto.fulldescrip,
      descrip: producto.descrip,
      skuph: producto.skuph,
      precioph: producto.precioph,
      muestra: producto.muestra,
      bodega1: producto.bodega1,
      bodega2: producto.bodega2,
      bodega3: producto.bodega3,
      bodega4: producto.bodega4,
    );
  }
}